version: '3'

services:
  web:
    container_name: web
    build:
      context: ./app/web
    links:
      - api
    depends_on:
      - api
    ports:
      - "80:80"
    working_dir: /etc/nginx
    volumes:
      - ./app/web/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./app/web/sites-available:/etc/nginx/sites-available
    restart: on-failure
  api:
    container_name: api
    build:
      context: ./app/api
      args:
        MODE: dev
    ports:
      - "9000:9000"
    working_dir: /usr/src/api
    volumes:
      - ./app/api/www:/usr/src/api


volumes:
  dbfront:
    driver: local
